repo_url    = "https://github.com/maremivazquez1/DigitalTherapyAssistant.git"
key_name    = "DTAkey"
db_name     = "dtaDB"
oauth_token = "xxx"
rds_exists  = "false"
vpc_id      = "vpc-0713b62da1a7928b9"