repo_url    = "https://github.com/maremivazquez1/DigitalTherapyAssistant.git"
key_name    = "DTAkey"
db_name     = "dtaDB"
oauth_token = "xxx"
vpc_id      = "vpc-06c6b7e28563e968c"
s3_bucket   = "cbt-beanstalk-bucket"
s3_key      = "springboot-app.zip"