# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#

name: 'Terraform Deployment'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PIPELINE }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PIPELINE }}
  HUME_API_KEY: ${{ secrets.HUME_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

on:
  push:
    branches: [ "pipeline" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Restore cached Terraform plugins
    - name: Restore Terraform cache
      uses: actions/cache@v3
      with:
        path: backend/aws-infra/.terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('backend/aws-infra/*.tf') }}

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to your region

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=backend/aws-infra/ init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform -chdir=backend/aws-infra/ fmt -check

    - name: Check if RDS exists and import
      id: check_rds
      run: |
        if aws rds describe-db-instances --db-instance-identifier "cbt" > /dev/null 2>&1; then
          terraform -chdir=backend/aws-infra/ import module.rds.aws_db_instance.rds_instance cbt
        fi

    - name: Check if ELB exists and import
      id: check_elb
      env:
        AWS_REGION: us-east-1
      run: |
        if aws elbv2 describe-load-balancers --names app-alb >/dev/null 2>&1; then
          ALB_ARN=$(aws elbv2 describe-load-balancers \
                      --names app-alb \
                      --query 'LoadBalancers[0].LoadBalancerArn' \
                      --output text)
          terraform -chdir=backend/aws-infra/ import aws_lb.app_alb "$ALB_ARN"
        fi

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=backend/aws-infra/ plan -input=false

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/pipeline' && github.event_name == 'push'
      run: |
          terraform -chdir=backend/aws-infra/ apply \
            -var="oauth_token=${{ secrets.OAUTH_TOKEN_GITHUB }}" \
            -var="aws_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret=${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -var="hume_key=${{ env.HUME_API_KEY }}" \
            -var="gemini_key=${{ env.GEMINI_API_KEY }}" \
            -auto-approve \
            -input=false